# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-added-large-files
- repo: https://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-lint
    - id: go-unit-tests
- repo: https://github.com/lauritzsh/markdownlint-plugin
  rev: d2945f77abee898fef48212adccbc2e3195c33c3
  hooks:
    - id: markdownlint
- repo: local
  hooks:
    - id: drone-lint
      name: Drone linting
      language: system
      entry: drone lint
      files: .drone.yml
